// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCTe2C3gezAD5aq3bM0X7J094D9qcQ9Ps',
    appId: '1:664260900377:web:08bf276200cfc7ee1b9c88',
    messagingSenderId: '664260900377',
    projectId: 'e-commerce-707',
    authDomain: 'e-commerce-707.firebaseapp.com',
    storageBucket: 'e-commerce-707.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARiN_yzJP79q-pBLtjCgc5Yj2zvaynXik',
    appId: '1:664260900377:android:83d8e1bc9f5e97ff1b9c88',
    messagingSenderId: '664260900377',
    projectId: 'e-commerce-707',
    storageBucket: 'e-commerce-707.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1nZEBvUmXWy4gloaiu4jS_xyNlJVC0hk',
    appId: '1:664260900377:ios:ed0f9aa66bc02b421b9c88',
    messagingSenderId: '664260900377',
    projectId: 'e-commerce-707',
    storageBucket: 'e-commerce-707.appspot.com',
    iosBundleId: 'com.example.eCommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1nZEBvUmXWy4gloaiu4jS_xyNlJVC0hk',
    appId: '1:664260900377:ios:ed0f9aa66bc02b421b9c88',
    messagingSenderId: '664260900377',
    projectId: 'e-commerce-707',
    storageBucket: 'e-commerce-707.appspot.com',
    iosBundleId: 'com.example.eCommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBCTe2C3gezAD5aq3bM0X7J094D9qcQ9Ps',
    appId: '1:664260900377:web:293ea62b047ebbfa1b9c88',
    messagingSenderId: '664260900377',
    projectId: 'e-commerce-707',
    authDomain: 'e-commerce-707.firebaseapp.com',
    storageBucket: 'e-commerce-707.appspot.com',
  );

}